version: "3"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:mysql://db:3306/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      
  db:
    image: mysql:5.7
    restart: always
    networks:
      - sonarnet
    environment:
      - MYSQL_ROOT_PASSWORD: sonar
      - MYSQL_DATABASE: sonar
      - MYSQL_USER: sonar
      - MYSQL_PASSWORD: sonar
    volumes:
      - db_data:/var/lib/mysql

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  db_data:
